spring:
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/insights
  #   username: insights
  #   password: insights
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

server:
  port: 8080

github:
  api:
    base-url: https://api.github.com
    token: ""